channels:
- conda-forge
dependencies:
- nbgitpuller
- jupyter
- python-duckdb
- duckdb-engine
- jupysql
- pandas
- matplotlib
- polars
- pygwalker
- pip
- pip:
  - git+https://github.com/frankier/nbgitpuller@forward-token
